### ISSUE TITLE
[Request] Back to October link/button

### ISSUE THREAD

**Issue by DanielHitchen** [skydiver/october-plugin-adminer#1]
Hi,

Great plugin, very useful! Just one suggestion, when on the login screen, I think it would be useful to either incorporate the October CMS nav at the top, or have some sort of back link to take you back to the CMS backend.

**Comment by skydiver** [comment]
Hello Daniel.

I'm planning this, but not sure how to do it.

Don't want to touch adminer source code.

One alternative can be an iframe.

**Comment by skydiver** [comment]
I've added a "iframe mode" on v1.1.0.

**Comment by DanielHitchen** [comment]
Thanks for adding this, works perfectly - I would just make the iFrame option as the default, as I don't really see the point in having it full screen as yoru stuck in the same situation as my initial comment i.e you can't get back to the October backend with ease - just a thought - but good job :)
