### ISSUE TITLE
Error with SQLite with new version

### ISSUE THREAD

**Issue by ghost** [skydiver/october-plugin-adminer#10]
Hello,

 I have a website using SQLite database and Adminer plugin. Website launched since months, everything worked perfectly until recently.

Now, when I go to the adminer page, It return an error :

> session_start(): open(/var/lib/php/session/sess_p80es0trm1e5hppnb4f5m5bgf0, O_RDWR) failed: No such file or directory (2)
> /plugins/martin/adminer/classes/adminer-4.3.1-en.php line 159

Don't know why, the only think I touched about this website is to update plugins. So it's probably related to a change in a recent update.

Best regards,

Alex

**Comment by skydiver** [comment]
Hello @Alex360hd 

I've installed a fresh copy of October and Adminer plugin but can't reproduce this error.

Looks session related, have you tried to logout and login (or open on incognito) ?
