### ISSUE TITLE
Feature request: automatic login for custom database

### ISSUE THREAD

**Issue by scanzy** [skydiver/october-plugin-adminer#13]
Hi,

it would be useful to have the plugin loading a custom database automaticly.

I use Adminer to browse an external sqlite database, so I have to write the db path every time.

I hope you could implement this (if it's not too long). What do you think?

**Comment by skydiver** [comment]
Hello @scanzy 

You say a custom configuration to autologin who override the default October database?

**Comment by scanzy** [comment]
Yes, for example `myfolder/mydatabase.sqlite`

**Comment by skydiver** [comment]
@scanzy after analyze the problem, i think the easier solution is to define a new connection on `config/database.php` and select this connection (overriding default) from plugin settings.

What do you think?

**Comment by scanzy** [comment]
Thank you @skydiver, the idea looks perfect 

I have tried but unfortunately adding a new connection in `config/database.php` doesn't show any new item in the plugin settings page.

Do you think this is normal or is it due to some bug?

Here is my `config/database.php` file:

this is the default configuration, with the added entry for autologin

```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | PDO Fetch Style
    |--------------------------------------------------------------------------
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */

    'fetch' => PDO::FETCH_CLASS,

    /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'sqlite',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => [

        'sqlite' => [
            'driver'   => 'sqlite',
            'database' => 'storage/database.sqlite',
            'prefix'   => '',
        ],

        'mysql' => [
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'port'      => 3306,
            'database'  => 'database',
            'username'  => 'root',
            'password'  => '',
            'charset'   => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix'    => '',
        ],

        'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'port'     => 5432,
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ],

        'sqlsrv' => [
            'driver'   => 'sqlsrv',
            'host'     => 'localhost',
            'port'     => 1433,
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'prefix'   => '',
        ],

        /* NEW CONNECTION FOR ADMINER AUTOLOGIN */
        'dbedit' => [
            'driver'   => 'sqlite',
            'database' => 'dbedit/database.sqlite',
            'prefix'   => '',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk have not actually be run in the databases.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => [

        'cluster' => false,

        'default' => [
            'host'     => '127.0.0.1',
            'password' => null,
            'port'     => 6379,
            'database' => 0,
        ],

    ],
];
```

Thank you for all

**Comment by scanzy** [comment]
Ok, I got it to work. Now the plugin (as you suggested) reads the custom connection in `config/database.sqlite`

I added a switch in the settings page to use the custom database (not the default), with a text field for the custom database connection name.

The descriptions are only in english (I don't speak fr or hu)

I would be happy to send to you a pull request to merge the edits, if you want.

Maybe the switch and the field I added in the settings are not organized in the best way, I hope you could improve it if you have time (unfortunately I have no experience with october and its yaml form system)

Thank you for all

**Comment by skydiver** [comment]
Hey @scanzy 

I was able to spend a few hours on the weekend.

I was working on a similar solution + reorganize the settings page.

I'm adding a few screenshots.

If you wanna send a PR i can take a look to merge both changes.

Thanks.-


![screen shot 2018-08-05 at 19 51 45](https://user-images.githubusercontent.com/578784/43690919-2a7781ca-98e9-11e8-86a8-aeedfbbcd940.png)

![screen shot 2018-08-05 at 19 51 35](https://user-images.githubusercontent.com/578784/43690922-36c55b82-98e9-11e8-9628-0bdb74eaeeb2.png)

**Comment by scanzy** [comment]
Oh well, this is great. 

I don't think you could add something from my edits since they are so few...

In addition your solution is more complete (with the dropdown of all the connections)

However I would be happy to send a PR with the Italian translation (I'll wait you push your edits to the repo so I can translate the new settings pages)

**Comment by skydiver** [comment]
@scanzy i've pushed the changes to the BETA branch
you can test by cloning this repo and change the branch

**Comment by scanzy** [comment]
Works like a charm, you're the best, thank you!

**Comment by skydiver** [comment]
@scanzy have you tried the new themes selector? did it work for you?

**Comment by scanzy** [comment]
Yes, it's useful and also nice looking. I'm using Firefox and I don't see any problem with the css. 

![cattura](https://user-images.githubusercontent.com/13015360/43841568-bf44c2d6-9b23-11e8-99b2-506761d45140.PNG)
