### ISSUE TITLE
error after installation at start

### ISSUE THREAD

**Issue by OVillani** [skydiver/october-plugin-adminer#19]
after installing and starting adminer this error message is shown:

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?
/data/web/e30506/html/tomdev/master/plugins/martin/adminer/classes/adminer-4.7.0-en.php line 1170

**Comment by skydiver** [comment]
Hello @ovillani 

Which php version are you using?
Which october build are you using?

**Comment by PubliAlex** [comment]
It's because adminer is incompatible with php 7.3 you have to downgrade to php 7.2 or wait for a module update

**Comment by OVillani** [comment]
Thanks @skydiver! I'll check this and change or wait if it's the case.

**Comment by skydiver** [comment]
Hello @ovillani 

As @PubliAlex says, current version of Adminer doesn't work.

I've already prepared a new version ([1.7.4](https://github.com/skydiver/october-plugin-adminer/pull/20)) but autologin is not working.

Will see if i can fix this or release without this feature.

**Comment by skydiver** [comment]
Ok, new version 1.7.4 was pushed to October marketplace.

Hope this fixes the errors.

**Comment by PubliAlex** [comment]
Doesn't work even with auto login OFF with SQLite database
