### ISSUE TITLE
Can't access SQLite adminer on October 2

### ISSUE THREAD

**Issue by CarolinePublipresse** [skydiver/october-plugin-adminer#22]
Hello, 

I can't access to Adminer since the new version, in any of my installations. It's installed with composer and it's all with SQLite databases. I checked Iframe and Autologin in the config. 
I'm on October v2.0.14.
The error returned is "invalid security key". 

Thanks for you help

**Comment by markandmedia** [comment]
This is not just in SQLite, it happens with Mysql as well.

**Comment by PubliAlex** [comment]
Same here, any solution yet ?

**Comment by Zmove** [comment]
Same problem here,  @skydiver do you have some time to investigate the issue ? adminer is impossible to use actually, that's a pity for a 9k+ downloaded plugin. Tried to investigate the code to make it works but it's quite complex, would take me days to fix it (if I can find a fix, which is not sure) ^^'

Best regards

**Comment by amdiv** [comment]
+1

**Comment by skydiver** [comment]
Sorry guys, i'm not planning to support any of my plugins on October v2.
